Class {
	#name : 'FamixValueJavaInfo',
	#superclass : 'Object',
	#category : 'Famix-Value-Interpreter',
	#package : 'Famix-Value-Interpreter'
}

{ #category : 'testing' }
FamixValueJavaInfo >> isAnnotationInterface [

	^ false
]

{ #category : 'testing' }
FamixValueJavaInfo >> isClass [

	^ false
]

{ #category : 'testing' }
FamixValueJavaInfo >> isConstructor [

	^ false
]

{ #category : 'testing' }
FamixValueJavaInfo >> isDeclaredType [

	^ false
]

{ #category : 'testing' }
FamixValueJavaInfo >> isEnum [

	^ false
]

{ #category : 'testing' }
FamixValueJavaInfo >> isExecutable [

	^ false
]

{ #category : 'testing' }
FamixValueJavaInfo >> isField [

	^ false
]

{ #category : 'testing' }
FamixValueJavaInfo >> isInterface [

	^ false
]

{ #category : 'testing' }
FamixValueJavaInfo >> isMember [

	^ false
]

{ #category : 'testing' }
FamixValueJavaInfo >> isMethod [

	^ false
]

{ #category : 'testing' }
FamixValueJavaInfo >> isRecord [

	^ false
]
