Extension { #name : 'FamixValueUnknownType' }

{ #category : '*Famix-Value-Entities-Extensions' }
FamixValueUnknownType >> concreteTypeName [

	^ name
]

{ #category : '*Famix-Value-Entities-Extensions' }
FamixValueUnknownType >> isParametricEntity [

	^ false
]

{ #category : '*Famix-Value-Entities-Extensions' }
FamixValueUnknownType >> isPrimitiveType [

	^ false
]

{ #category : '*Famix-Value-Entities-Extensions' }
FamixValueUnknownType >> methods [

	^ {  }
]

{ #category : '*Famix-Value-Entities-Extensions' }
FamixValueUnknownType >> typeName [

	^ name
]
